#!/bin/bash
w=$(printf '%s' "$WATER" | tr 'water' '01234' | tr -cd '0-4'); s=$(printf '%s' "$STIR" | tr 'stir' '01234' | tr -cd '0-4'); printf '%s\n' "$(printf '%o' $((5#$w + 5#$s)))" | tr '01234567' 'bestchol'
