#!/usr/bin/env bash
# Configure an Ubuntu server with the below requirements:
#   localhost resolves to 127.0.0.2
#   facebook.com resolves to 8.8.8.8
#   The checker is running on Docker which overwrites /etc/hosts whenever it wants
cp /etc/hosts ~/hosts.new
sed -i s/^172.*$// ~/hosts.new
echo "8.8.8.8         facebook.com" >> ~/hosts.new
cp -f ~/host.new /etc/hosts